DELETE FROM OWNER;
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (1,'GARETH','BADENHORST');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (2,'SANDRA','BRUYNS');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (3,'DEAN','BRUYNS');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (4,'JOSHUA','BRUYNS');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (5,'DYLAN','BRUYNS');