INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (1,'GARETH','BADENHORST');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (2,'SANDRA','BRUYNS');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (3,'PAUL','BADENHORST');
INSERT INTO OWNER(ID,FIRST_NAME,LAST_NAME) VALUES (4,'DEAN','BRUYNS');